# Get all books
GET https://talented-toad-apron.cyclic.app/books HTTP/1.1
Content-Type: application/json

###

# Create a book
POST https://talented-toad-apron.cyclic.app/books HTTP/1.1
Content-Type: application/json

{
  "title": "Harry Potter"
}

###

# Update a book
PUT https://talented-toad-apron.cyclic.app/books/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Dark Tower"
}

###

# Delete a book
DELETE https://talented-toad-apron.cyclic.app/books/1 HTTP/1.1
Content-Type: application/json